export const ACHIEVEMENTS = [
  {
    id: 'reset_confirmed',
    type: 'total_resets',
    threshold: 3,
    title: 'Are you sure about that?',
    description: 'Full run resets. Double-check before you smash that button next time.',
    image: '/assets/achievements/areyousureaboutthat.gif',
  },
  {
    id: 'obeerma',
    type: 'run_drinks',
    variationType: 'beer',
    // Threshold counts beers in the current run (drinkVariations.beer). Unlocks on the 10th beer of a run.
    threshold: 10,
    title: 'Obeerma',
    description: 'Beers down the hatch. Change is brewing.',
    image: '/assets/achievements/obeerma.png',
  },
  {
    id: 'full_bender',
    type: 'run_drinks',
    threshold: 20,
    title: 'Full Bender',
    description: 'Twenty drinks. Maybe switch to water for one round?',
    image: '/assets/achievements/fullbender.gif',
  },
  {
    id: 'like_fine_wine',
    type: 'total_drinks',
    variationType: 'wine',
    threshold: 5,
    title: 'Like Fine Wine',
    description: 'Five wines deep and still aging gracefully.',
    image: '/assets/achievements/likefinewine.png',
  },
  {
    id: 'top_donor',
    type: 'manual',
    title: 'Top Donor',
    description: 'Du har doneret til Sladesh App, mange tak for dit bidrag',
    image: '/assets/achievements/topdonor.jpeg',
  },
  {
    id: 'mr_worldwide',
    type: 'category_diversity',
    requiredCategories: ['beer', 'cider', 'wine', 'cocktail', 'shot'],
    title: 'Mr. Worldwide',
    description: 'Du har smagt på det hele! En genstand registreret i hver kategori: Øl, Cider, Vin, Cocktails og Shots.',
    image: '/assets/achievements/mrworldwide.jpg',
  },
  {
    id: 'puff_minister',
    type: 'run_specific_variation',
    category: 'other',
    variation: 'Cigaret',
    threshold: 5,
    title: 'Puffminister',
    description: 'Du har haft ekstra travlt med piberiet i dag! Mere end 5 pufs registreret på én dag.',
    image: '/assets/achievements/puffpuffpassaway.jpg',
  },
  {
    id: 'feinschmecker',
    type: 'specific_drink_count',
    category: 'cocktail',
    variation: 'Vermouth Tonic',
    threshold: 1,
    title: 'Feinschmecker',
    description: 'En sand kender! Du har nydt en klassisk Vermouth og Tonic.',
    image: '/assets/achievements/feinschmecker.png',
  },
]
